import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Meow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/vazir-font@30.1.0/dist/font-face.min.css"
        ></link>
      </body>
    </html>
  );
}
